chore: run tests on pre-push git hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -10,11 +10,25 @@ echo -e "${YELLOW}Building project...${NOCOLOR}"
 DOTNET_CLI_TELEMETRY_OPTOUT=1
 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
 
-dotnet build
+dotnet build RegisterApi
+dotnet build Tests/Integration
 
 if [ $? -ne 0 ] ; then
     echo ""
 	echo -e "${RED}The build failed. Please fix the problems before pushing the changes${NOCOLOR}"
+	echo ""
+	exit 1
+fi
+
+echo ""
+echo -e "${YELLOW}Executing Integration Tests ...${NOCOLOR}"
+echo ""
+
+dotnet test Tests/Integration
+
+if [ $? -ne 0 ] ; then
+    echo ""
+	echo -e "${RED}One or more integration tests failed. Please fix the problems before pushing the changes${NOCOLOR}"
 	echo ""
 	exit 1
 fi
